name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Update-website
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/html/valera/
            git checkout main
            git pull
  notify:
    needs: deploy
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - name: notify
        run: echo Done!
    
        
      
      
